# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Steam: /steamgames
  Bangumi: /bangumis
  Link: https://bili33.top/link
  About: https://bili33.top/About/
rss: /atom.xml

#Theme
theme_color: y-pink
loader: loadbartop
loader_text: We're loading for your best experience
search: true
#Navbar
nav_fixed: true

# Content
excerpt_link: Read full article
excerpt_link_shape: oval
excerpt_link_shadow: true
fancybox: true
# Blogger
avatar: https://cdn.jsdelivr.net/gh/GamerNoTitle/Picture-repo@1.0/AboutMe/logo-mini.png
introduce: A senior high school student fighting for GaoKao in 2021
followurl: https://github.com/GamerNoTitle
avatarjumpurl: https://bili33.top
# Sidebar
sidebar: left
widgets:
- blogger
- theme
- blog_info
- tagcloud
- archive
- category
- recent_posts
drawerwidgets:
- blogger
- theme
- navlist
- blog_info

#Baidu Search Resource Platform
baidu_search:
  enable: false
  baidu_site_verification: 

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: https://cdn.jsdelivr.net/gh/GamerNoTitle/Picture-repo@1.0/AboutMe/logo-mini.png

#Google AdSense
AdSense:
  enable: true
  adclient: ca-pub-5864391143249049

#Valine
valine:
  enable: true
  AppId: wRUW5fICAL8URzxXwJNSiwA7-MdYXbMMI
  AppKey: LbtRzTQKxCWNpj30GLH3sw5j
  lang: en
  placeholder: ğŸ“ŒYou can input you QQ number in nickname that it will fill in your QQ information\nğŸ‘¨â€ğŸ”§This site has enabled Akismet\nğŸš€Markdown is supported # valine comment input placeholder(like: Please leave your footprints )
  recordIP: true
  enableQQ: true
  emojiCDN: https://valinecdn.bili33.top/
  emojiMaps: {
    "bilibiliHotKey1": "bilibiliHotKey/1.jpg",
    "bilibiliHotKey2": "bilibiliHotKey/10.jpg",
    "bilibiliHotKey3": "bilibiliHotKey/11.jpg",
    "bilibiliHotKey4": "bilibiliHotKey/12.jpg",
    "bilibiliHotKey5": "bilibiliHotKey/13.jpg",
    "bilibiliHotKey6": "bilibiliHotKey/14.jpg",
    "bilibiliHotKey7": "bilibiliHotKey/15.jpg",
    "bilibiliHotKey8": "bilibiliHotKey/16.jpg",
    "bilibiliHotKey9": "bilibiliHotKey/17.jpg",
    "bilibiliHotKey10": "bilibiliHotKey/18.jpg",
    "bilibiliHotKey11": "bilibiliHotKey/19.jpg",
    "bilibiliHotKey12": "bilibiliHotKey/2.jpg",
    "bilibiliHotKey13": "bilibiliHotKey/20.jpg",
    "bilibiliHotKey14": "bilibiliHotKey/21.jpg",
    "bilibiliHotKey15": "bilibiliHotKey/22.jpg",
    "bilibiliHotKey16": "bilibiliHotKey/23.jpg",
    "bilibiliHotKey17": "bilibiliHotKey/24.jpg",
    "bilibiliHotKey18": "bilibiliHotKey/25.jpg",
    "bilibiliHotKey19": "bilibiliHotKey/26.jpg",
    "bilibiliHotKey20": "bilibiliHotKey/27.jpg",
    "bilibiliHotKey21": "bilibiliHotKey/28.jpg",
    "bilibiliHotKey22": "bilibiliHotKey/29.jpg",
    "bilibiliHotKey23": "bilibiliHotKey/3.jpg",
    "bilibiliHotKey24": "bilibiliHotKey/30.jpg",
    "bilibiliHotKey25": "bilibiliHotKey/31.jpg",
    "bilibiliHotKey26": "bilibiliHotKey/32.jpg",
    "bilibiliHotKey27": "bilibiliHotKey/4.jpg",
    "bilibiliHotKey28": "bilibiliHotKey/5.jpg",
    "bilibiliHotKey29": "bilibiliHotKey/6.jpg",
    "bilibiliHotKey30": "bilibiliHotKey/7.jpg",
    "bilibiliHotKey31": "bilibiliHotKey/8.jpg",
    "bilibiliHotKey32": "bilibiliHotKey/9.jpg",
    "bilibilitv2": "bilibilitv/[tv_doge].png",
    "bilibilitv3": "bilibilitv/[tv_äº²äº²].png",
    "bilibilitv4": "bilibilitv/[tv_å·ç¬‘].png",
    "bilibilitv5": "bilibilitv/[tv_å†è§].png",
    "bilibilitv6": "bilibilitv/[tv_å†·æ¼ ].png",
    "bilibilitv7": "bilibilitv/[tv_å‘æ€’].png",
    "bilibilitv8": "bilibilitv/[tv_å‘è´¢].png",
    "bilibilitv9": "bilibilitv/[tv_å¯çˆ±].png",
    "bilibilitv10": "bilibilitv/[tv_åè¡€].png",
    "bilibilitv11": "bilibilitv/[tv_å‘†].png",
    "bilibilitv12": "bilibilitv/[tv_å‘•å].png",
    "bilibilitv13": "bilibilitv/[tv_å›°].png",
    "bilibilitv14": "bilibilitv/[tv_åç¬‘].png",
    "bilibilitv15": "bilibilitv/[tv_å¤§ä½¬].png",
    "bilibilitv16": "bilibilitv/[tv_å¤§å“­].png",
    "bilibilitv17": "bilibilitv/[tv_å§”å±ˆ].png",
    "bilibilitv18": "bilibilitv/[tv_å®³ç¾].png",
    "bilibilitv19": "bilibilitv/[tv_å°´å°¬].png",
    "bilibilitv20": "bilibilitv/[tv_å¾®ç¬‘].png",
    "bilibilitv21": "bilibilitv/[tv_æ€è€ƒ].png",
    "bilibilitv22": "bilibilitv/[tv_æƒŠå“].png",
    "bilibilitv23": "bilibilitv/[tv_æ‰“è„¸].png",
    "bilibilitv24": "bilibilitv/[tv_æŠ“ç‹‚].png",
    "bilibilitv25": "bilibilitv/[tv_æŠ é¼»].png",
    "bilibilitv26": "bilibilitv/[tv_æ–œçœ¼ç¬‘].png",
    "bilibilitv27": "bilibilitv/[tv_æ— å¥ˆ].png",
    "bilibilitv28": "bilibilitv/[tv_æ™•].png",
    "bilibilitv29": "bilibilitv/[tv_æµæ±—].png",
    "bilibilitv30": "bilibilitv/[tv_æµæ³ª].png",
    "bilibilitv31": "bilibilitv/[tv_æµé¼»è¡€].png",
    "bilibilitv32": "bilibilitv/[tv_ç‚¹èµ].png",
    "bilibilitv33": "bilibilitv/[tv_ç”Ÿæ°”].png",
    "bilibilitv34": "bilibilitv/[tv_ç”Ÿç—…].png",
    "bilibilitv35": "bilibilitv/[tv_ç–‘é—®].png",
    "bilibilitv36": "bilibilitv/[tv_ç™½çœ¼].png",
    "bilibilitv37": "bilibilitv/[tv_çš±çœ‰].png",
    "bilibilitv38": "bilibilitv/[tv_ç›®çªå£å‘†].png",
    "bilibilitv39": "bilibilitv/[tv_ç¡ç€].png",
    "bilibilitv40": "bilibilitv/[tv_ç¬‘å“­].png",
    "bilibilitv41": "bilibilitv/[tv_è…¼è…†].png",
    "bilibilitv42": "bilibilitv/[tv_è‰²].png",
    "bilibilitv43": "bilibilitv/[tv_è°ƒä¾ƒ].png",
    "bilibilitv44": "bilibilitv/[tv_è°ƒçš®].png",
    "bilibilitv45": "bilibilitv/[tv_é„™è§†].png",
    "bilibilitv46": "bilibilitv/[tv_é—­å˜´].png",
    "bilibilitv47": "bilibilitv/[tv_éš¾è¿‡].png",
    "bilibilitv48": "bilibilitv/[tv_é¦‹].png",
    "bilibilitv49": "bilibilitv/[tv_é¬¼è„¸].png",
    "bilibilitv50": "bilibilitv/[tv_é»‘äººé—®å·].png",
    "bilibilitv51": "bilibilitv/[tv_é¼“æŒ].png",
    "Menhera-chan1": "Menhera-chan/1.jpg",
    "Menhera-chan2": "Menhera-chan/10.jpg",
    "Menhera-chan3": "Menhera-chan/100.jpg",
    "Menhera-chan4": "Menhera-chan/101.jpg",
    "Menhera-chan5": "Menhera-chan/102.jpg",
    "Menhera-chan6": "Menhera-chan/103.jpg",
    "Menhera-chan7": "Menhera-chan/104.jpg",
    "Menhera-chan8": "Menhera-chan/105.jpg",
    "Menhera-chan9": "Menhera-chan/106.jpg",
    "Menhera-chan10": "Menhera-chan/107.jpg",
    "Menhera-chan11": "Menhera-chan/108.jpg",
    "Menhera-chan12": "Menhera-chan/109.jpg",
    "Menhera-chan13": "Menhera-chan/11.jpg",
    "Menhera-chan14": "Menhera-chan/110.jpg",
    "Menhera-chan15": "Menhera-chan/111.jpg",
    "Menhera-chan16": "Menhera-chan/112.jpg",
    "Menhera-chan17": "Menhera-chan/113.jpg",
    "Menhera-chan18": "Menhera-chan/114.jpg",
    "Menhera-chan19": "Menhera-chan/115.jpg",
    "Menhera-chan20": "Menhera-chan/116.jpg",
    "Menhera-chan21": "Menhera-chan/117.jpg",
    "Menhera-chan22": "Menhera-chan/118.jpg",
    "Menhera-chan23": "Menhera-chan/119.jpg",
    "Menhera-chan24": "Menhera-chan/12.jpg",
    "Menhera-chan25": "Menhera-chan/120.jpg",
    "Menhera-chan26": "Menhera-chan/13.jpg",
    "Menhera-chan27": "Menhera-chan/14.jpg",
    "Menhera-chan28": "Menhera-chan/15.jpg",
    "Menhera-chan29": "Menhera-chan/16.jpg",
    "Menhera-chan30": "Menhera-chan/17.jpg",
    "Menhera-chan31": "Menhera-chan/18.jpg",
    "Menhera-chan32": "Menhera-chan/19.jpg",
    "Menhera-chan33": "Menhera-chan/2.jpg",
    "Menhera-chan34": "Menhera-chan/20.jpg",
    "Menhera-chan35": "Menhera-chan/21.jpg",
    "Menhera-chan36": "Menhera-chan/22.jpg",
    "Menhera-chan37": "Menhera-chan/23.jpg",
    "Menhera-chan38": "Menhera-chan/24.jpg",
    "Menhera-chan39": "Menhera-chan/25.jpg",
    "Menhera-chan40": "Menhera-chan/26.jpg",
    "Menhera-chan41": "Menhera-chan/27.jpg",
    "Menhera-chan42": "Menhera-chan/28.jpg",
    "Menhera-chan43": "Menhera-chan/29.jpg",
    "Menhera-chan44": "Menhera-chan/3.jpg",
    "Menhera-chan45": "Menhera-chan/30.jpg",
    "Menhera-chan46": "Menhera-chan/31.jpg",
    "Menhera-chan47": "Menhera-chan/32.jpg",
    "Menhera-chan48": "Menhera-chan/33.jpg",
    "Menhera-chan49": "Menhera-chan/34.jpg",
    "Menhera-chan50": "Menhera-chan/35.jpg",
    "Menhera-chan51": "Menhera-chan/36.jpg",
    "Menhera-chan52": "Menhera-chan/37.jpg",
    "Menhera-chan53": "Menhera-chan/38.jpg",
    "Menhera-chan54": "Menhera-chan/39.jpg",
    "Menhera-chan55": "Menhera-chan/4.jpg",
    "Menhera-chan56": "Menhera-chan/40.jpg",
    "Menhera-chan57": "Menhera-chan/41.jpg",
    "Menhera-chan58": "Menhera-chan/42.jpg",
    "Menhera-chan59": "Menhera-chan/43.jpg",
    "Menhera-chan60": "Menhera-chan/44.jpg",
    "Menhera-chan61": "Menhera-chan/45.jpg",
    "Menhera-chan62": "Menhera-chan/46.jpg",
    "Menhera-chan63": "Menhera-chan/47.jpg",
    "Menhera-chan64": "Menhera-chan/48.jpg",
    "Menhera-chan65": "Menhera-chan/49.jpg",
    "Menhera-chan66": "Menhera-chan/5.jpg",
    "Menhera-chan67": "Menhera-chan/50.jpg",
    "Menhera-chan68": "Menhera-chan/51.jpg",
    "Menhera-chan69": "Menhera-chan/52.jpg",
    "Menhera-chan70": "Menhera-chan/53(1).jpg",
    "Menhera-chan71": "Menhera-chan/53.jpg",
    "Menhera-chan72": "Menhera-chan/54.jpg",
    "Menhera-chan73": "Menhera-chan/55.jpg",
    "Menhera-chan74": "Menhera-chan/56.jpg",
    "Menhera-chan75": "Menhera-chan/57.jpg",
    "Menhera-chan76": "Menhera-chan/58.jpg",
    "Menhera-chan77": "Menhera-chan/59.jpg",
    "Menhera-chan78": "Menhera-chan/6.jpg",
    "Menhera-chan79": "Menhera-chan/60.jpg",
    "Menhera-chan80": "Menhera-chan/61.jpg",
    "Menhera-chan81": "Menhera-chan/62.jpg",
    "Menhera-chan82": "Menhera-chan/63.jpg",
    "Menhera-chan83": "Menhera-chan/64.jpg",
    "Menhera-chan84": "Menhera-chan/65.jpg",
    "Menhera-chan85": "Menhera-chan/66.jpg",
    "Menhera-chan86": "Menhera-chan/67.jpg",
    "Menhera-chan87": "Menhera-chan/68.jpg",
    "Menhera-chan88": "Menhera-chan/69.jpg",
    "Menhera-chan89": "Menhera-chan/7.jpg",
    "Menhera-chan90": "Menhera-chan/70.jpg",
    "Menhera-chan91": "Menhera-chan/71.jpg",
    "Menhera-chan92": "Menhera-chan/72.jpg",
    "Menhera-chan93": "Menhera-chan/73.jpg",
    "Menhera-chan94": "Menhera-chan/74.jpg",
    "Menhera-chan95": "Menhera-chan/75.jpg",
    "Menhera-chan96": "Menhera-chan/76.jpg",
    "Menhera-chan97": "Menhera-chan/77.jpg",
    "Menhera-chan98": "Menhera-chan/78.jpg",
    "Menhera-chan99": "Menhera-chan/79.jpg",
    "Menhera-chan100": "Menhera-chan/8.jpg",
    "Menhera-chan101": "Menhera-chan/80.jpg",
    "Menhera-chan102": "Menhera-chan/81.jpg",
    "Menhera-chan103": "Menhera-chan/82.jpg",
    "Menhera-chan104": "Menhera-chan/83.jpg",
    "Menhera-chan105": "Menhera-chan/84.jpg",
    "Menhera-chan106": "Menhera-chan/85.jpg",
    "Menhera-chan107": "Menhera-chan/86.jpg",
    "Menhera-chan108": "Menhera-chan/87.jpg",
    "Menhera-chan109": "Menhera-chan/88.jpg",
    "Menhera-chan110": "Menhera-chan/89.jpg",
    "Menhera-chan111": "Menhera-chan/9.jpg",
    "Menhera-chan112": "Menhera-chan/90.jpg",
    "Menhera-chan113": "Menhera-chan/91.jpg",
    "Menhera-chan114": "Menhera-chan/92.jpg",
    "Menhera-chan115": "Menhera-chan/93.jpg",
    "Menhera-chan116": "Menhera-chan/94.jpg",
    "Menhera-chan117": "Menhera-chan/95.jpg",
    "Menhera-chan118": "Menhera-chan/96.jpg",
    "Menhera-chan119": "Menhera-chan/97.jpg",
    "Menhera-chan120": "Menhera-chan/98.jpg",
    "Menhera-chan121": "Menhera-chan/99.jpg",
    "Tsuri-me-ju_mimi1": "Tsuri-me-ju_mimi/10753776_key@2x.png",
    "Tsuri-me-ju_mimi2": "Tsuri-me-ju_mimi/10753777_key@2x.png",
    "Tsuri-me-ju_mimi3": "Tsuri-me-ju_mimi/10753778_key@2x.png",
    "Tsuri-me-ju_mimi4": "Tsuri-me-ju_mimi/10753779_key@2x.png",
    "Tsuri-me-ju_mimi5": "Tsuri-me-ju_mimi/10753780_key@2x.png",
    "Tsuri-me-ju_mimi6": "Tsuri-me-ju_mimi/10753781_key@2x.png",
    "Tsuri-me-ju_mimi7": "Tsuri-me-ju_mimi/10753782_key@2x.png",
    "Tsuri-me-ju_mimi8": "Tsuri-me-ju_mimi/10753783_key@2x.png",
    "Tsuri-me-ju_mimi9": "Tsuri-me-ju_mimi/10753784_key@2x.png",
    "Tsuri-me-ju_mimi10": "Tsuri-me-ju_mimi/10753785_key@2x.png",
    "Tsuri-me-ju_mimi11": "Tsuri-me-ju_mimi/10753786_key@2x.png",
    "Tsuri-me-ju_mimi12": "Tsuri-me-ju_mimi/10753787_key@2x.png",
    "Tsuri-me-ju_mimi13": "Tsuri-me-ju_mimi/10753788_key@2x.png",
    "Tsuri-me-ju_mimi14": "Tsuri-me-ju_mimi/10753789_key@2x.png",
    "Tsuri-me-ju_mimi15": "Tsuri-me-ju_mimi/10753790_key@2x.png",
    "Tsuri-me-ju_mimi16": "Tsuri-me-ju_mimi/10753791_key@2x.png",
    "Tsuri-me-ju_mimi17": "Tsuri-me-ju_mimi/10753792_key@2x.png",
    "Tsuri-me-ju_mimi18": "Tsuri-me-ju_mimi/10753793_key@2x.png",
    "Tsuri-me-ju_mimi19": "Tsuri-me-ju_mimi/10753794_key@2x.png",
    "Tsuri-me-ju_mimi20": "Tsuri-me-ju_mimi/10753795_key@2x.png",
    "Tsuri-me-ju_mimi21": "Tsuri-me-ju_mimi/10753796_key@2x.png",
    "Tsuri-me-ju_mimi22": "Tsuri-me-ju_mimi/10753797_key@2x.png",
    "Tsuri-me-ju_mimi23": "Tsuri-me-ju_mimi/10753798_key@2x.png",
    "Tsuri-me-ju_mimi24": "Tsuri-me-ju_mimi/10753799_key@2x.png",
    "Tsuri-me-ju_mimi25": "Tsuri-me-ju_mimi/10753800_key@2x.png",
    "Tsuri-me-ju_mimi26": "Tsuri-me-ju_mimi/10753801_key@2x.png",
    "Tsuri-me-ju_mimi27": "Tsuri-me-ju_mimi/10753802_key@2x.png",
    "Tsuri-me-ju_mimi28": "Tsuri-me-ju_mimi/10753803_key@2x.png",
    "Tsuri-me-ju_mimi29": "Tsuri-me-ju_mimi/10753804_key@2x.png",
    "Tsuri-me-ju_mimi30": "Tsuri-me-ju_mimi/10753805_key@2x.png",
    "Tsuri-me-ju_mimi31": "Tsuri-me-ju_mimi/10753806_key@2x.png",
    "Tsuri-me-ju_mimi32": "Tsuri-me-ju_mimi/10753807_key@2x.png",
    "Tsuri-me-ju_mimi33": "Tsuri-me-ju_mimi/10753808_key@2x.png",
    "Tsuri-me-ju_mimi34": "Tsuri-me-ju_mimi/10753809_key@2x.png",
    "Tsuri-me-ju_mimi35": "Tsuri-me-ju_mimi/10753810_key@2x.png",
    "Tsuri-me-ju_mimi36": "Tsuri-me-ju_mimi/10753811_key@2x.png",
    "Tsuri-me-ju_mimi37": "Tsuri-me-ju_mimi/10753812_key@2x.png",
    "Tsuri-me-ju_mimi38": "Tsuri-me-ju_mimi/10753813_key@2x.png",
    "Tsuri-me-ju_mimi39": "Tsuri-me-ju_mimi/10753814_key@2x.png",
    "Tsuri-me-ju_mimi40": "Tsuri-me-ju_mimi/10753815_key@2x.png",
    "Arcaea1": "Arcaea/184064198.png",
    "Arcaea2": "Arcaea/184064199.png",
    "Arcaea3": "Arcaea/184064200.png",
    "Arcaea4": "Arcaea/184064201.png",
    "Arcaea5": "Arcaea/184064202.png",
    "Arcaea6": "Arcaea/184064203.png",
    "Arcaea7": "Arcaea/184064204.png",
    "Arcaea8": "Arcaea/184064205.png",
    "Arcaea9": "Arcaea/184064206.png",
    "Arcaea10": "Arcaea/184064207.png",
    "Arcaea11": "Arcaea/184064208.png",
    "Arcaea12": "Arcaea/184064209.png",
    "Arcaea13": "Arcaea/184064210.png",
    "Arcaea14": "Arcaea/184064211.png",
    "Arcaea15": "Arcaea/184064212.png",
    "Arcaea16": "Arcaea/184064213.png",
    "Arcaea17": "Arcaea/184064214.png",
    "Arcaea18": "Arcaea/184064215.png",
    "Arcaea19": "Arcaea/184064216.png",
    "Arcaea20": "Arcaea/184064217.png",
    "Arcaea21": "Arcaea/184064218.png",
    "Arcaea22": "Arcaea/184064219.png",
    "Arcaea23": "Arcaea/184064220.png",
    "Arcaea24": "Arcaea/184064221.png",
    "Arcaea25": "Arcaea/184064222.png",
    "Arcaea26": "Arcaea/184064223.png",
    "Arcaea27": "Arcaea/184064224.png",
    "Arcaea28": "Arcaea/184064225.png",
    "Arcaea29": "Arcaea/184064226.png",
    "Arcaea30": "Arcaea/184064227.png",
    "Arcaea31": "Arcaea/184064228.png",
    "Arcaea32": "Arcaea/184064229.png",
    "Arcaea33": "Arcaea/184064230.png",
    "Arcaea34": "Arcaea/184064231.png",
    "Arcaea35": "Arcaea/184064232.png",
    "Arcaea36": "Arcaea/184064233.png",
    "Arcaea37": "Arcaea/184064234.png",
    "Arcaea38": "Arcaea/184064235.png",
    "Arcaea39": "Arcaea/184064236.png",
    "Arcaea40": "Arcaea/184064237.png"
}
